export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_RATINGS_SUCCESS = 'FETCH_RATINGS_SUCCESS';
export const CREATE_RATING_SUCCESS ='CREATE_RATING_SUCCESS';
export const FETCH_USER_BY_ID_SUCCESS ='FETCH_USER_BY_ID_SUCCESS';
export const FETCH_ALL_PRODUCTS_BY_ID_CATEGORY_SUCCESS ='FETCH_ALL_PRODUCTS_BY_ID_CATEGORY_SUCCESS';
export const FETCH_ALL_RATINGS_BY_ID_PRODUCT_SUCCESS ='FETCH_ALL_RATINGS_BY_ID_PRODUCT_SUCCESS';
export const FETCH_CATEGORYS_SUCCESS ='FETCH_CATEGORYS_SUCCESS';

